modLoader = "kotlinforforge"
loaderVersion = "[1,)"
license = "${mod_license}"
issueTrackerURL=""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_desc}"
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "${mod_id}-neoforge.mixins.json"